import {useEffect,useState} from 'react'
import {type Annotation} from '../lib/api'
import {ColorPicker,colors,EmptyState} from './WorkspaceUI'
interface Props{annotations:Annotation[];selectedId:string|null;onSelect:(annotation:Annotation)=>void;onUpdate:(id:string,data:{note?:string;color?:string})=>Promise<void>;onDelete:(id:string)=>Promise<void>;onDirtyChange?:(dirty:boolean)=>void}
export default function AnnotationPanel({annotations,selectedId,onSelect,onUpdate,onDelete,onDirtyChange}:Props){
 const active=annotations.find(a=>a.id===selectedId),[draft,setDraft]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState(''),[filter,setFilter]=useState('all')
 useEffect(()=>{setDraft(active?.note||'');setError('')},[active?.id,active?.note])
 const dirty=draft!==(active?.note||'')
 useEffect(()=>{onDirtyChange?.(dirty);return()=>onDirtyChange?.(false)},[dirty,onDirtyChange])
 useEffect(()=>{if(!dirty)return;const guard=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=''};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[dirty])
 async function save(){if(!active)return;setSaving(true);setError('');try{await onUpdate(active.id,{note:draft})}catch(e){setError(e instanceof Error?e.message:'保存失败，请重试。')}finally{setSaving(false)}}
 function select(annotation:Annotation){if(dirty&&!confirm('注释尚未保存。放弃修改并查看其他标注吗？'))return;onSelect(annotation)}
 const shown=annotations.filter(a=>filter!=='notes'||!!a.note?.trim()).sort((a,b)=>a.page_number-b.page_number||a.y1-b.y1)
 return <div className="annotation-panel"><header className="panel-heading"><div><h2>阅读标注</h2><p>选中文字，留下你的理解。</p></div><span className="count-badge">{annotations.length}</span></header><div className="annotation-filters"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>全部标注</button><button className={filter==='notes'?'active':''} onClick={()=>setFilter('notes')}>有注释</button></div><div className="annotation-list">{!shown.length&&<EmptyState title={filter==='notes'?'暂无文字注释':'还没有标注'}>在 PDF 中选中文字，点击“高亮”或“添加注释”。</EmptyState>}{shown.map(annotation=><button key={annotation.id} className={`annotation-card ${selectedId===annotation.id?'selected':''}`} onClick={()=>select(annotation)} style={{borderLeftColor:colors[annotation.color as keyof typeof colors]||colors.yellow}}><span>第 {annotation.page_number} 页 {annotation.note?'· 有注释':''}</span><blockquote>{annotation.text}</blockquote>{annotation.note&&<p>{annotation.note}</p>}</button>)}</div>{active&&<div className="annotation-editor"><div className="editor-top"><strong>第 {active.page_number} 页的注释</strong><ColorPicker value={active.color} disabled={saving} onChange={color=>{onUpdate(active.id,{color}).catch(e=>setError(e.message))}}/></div><label htmlFor="annotation-note">我的理解</label><textarea id="annotation-note" name="annotationNote" autoComplete="off" placeholder="写下解释、疑问或思考…" value={draft} onChange={e=>setDraft(e.target.value)}/><div className="editor-actions"><button className="danger-text" disabled={saving} onClick={()=>{if(confirm('删除这条标注及注释吗？'))onDelete(active.id).catch(e=>setError(e.message))}}>删除标注</button><span aria-live="polite">{dirty?'未保存':'已保存'}</span><button className="primary" disabled={saving} onClick={save}>{saving?'正在保存…':'保存注释'}</button></div>{error&&<p role="alert" className="error-message">{error}</p>}</div>}</div>
}
