import {useEffect,useState} from 'react'
import {Link,useNavigate} from 'react-router-dom'
import {notesApi,sourcesApi,annotationsApi,type Note,type Source,type Annotation} from '../lib/api'
export default function ProjectNotes({projectId}:{projectId:string}){
 const [notes,setNotes]=useState<Note[]>([]),[sources,setSources]=useState<Source[]>([]),[legacy,setLegacy]=useState<Record<string,Annotation[]>>({}),[error,setError]=useState(''),[query,setQuery]=useState(''),[loading,setLoading]=useState(true)
 const navigate=useNavigate()
 useEffect(()=>{let cancelled=false;Promise.all([notesApi.list(projectId),sourcesApi.list(projectId)]).then(async([n,s])=>{const a=await Promise.all(s.map(async source=>[source.id,(await annotationsApi.list(projectId,source.id)).filter(a=>a.note)] as const));if(!cancelled){setNotes(n);setSources(s);setLegacy(Object.fromEntries(a));setLoading(false)}}).catch(e=>{if(!cancelled){setError(e.message);setLoading(false)}});return()=>{cancelled=true}},[projectId])
 const shown=notes.filter(n=>`${n.title} ${n.preview} ${(n.tags||[]).join(' ')}`.toLowerCase().includes(query.toLowerCase()))
 async function create(){try{const {id}=await notesApi.create(projectId,{title:'未命名项目笔记'});navigate(`/projects/${projectId}/notes/${id}`)}catch(e){setError((e as Error).message)}}
 function card(n:Note){return <Link className="project-note-card" key={n.id} to={`/projects/${projectId}/notes/${n.id}`}><strong>{n.title}</strong><p>{n.preview||'暂无正文'}</p><small>{(n.tags||[]).join(' · ')}</small></Link>}
 return <section className="project-notes"><header className="study-heading"><h1>笔记</h1><button className="primary" onClick={()=>void create()}>新建项目笔记</button></header><label className="note-search">搜索笔记<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="标题、内容或标签"/></label>{error&&<p role="alert">{error}</p>}{loading?<p>正在加载笔记…</p>:<><h2>项目笔记</h2><div className="note-group">{shown.filter(n=>!n.source_id).map(card)}{!shown.some(n=>!n.source_id)&&<p>学习计划和跨文献总结可以记录在这里。</p>}</div><h2>文献笔记</h2>{sources.map(source=><section className="source-note-group" key={source.id}><header><h3>{source.title}</h3><Link to={`/projects/${projectId}/sources/${source.id}?mode=notes`}>整理与复习</Link></header><div className="note-group">{shown.filter(n=>n.source_id===source.id).map(card)}{!query&&(legacy[source.id]||[]).map(a=><Link key={a.id} className="project-note-card" to={`/projects/${projectId}/sources/${source.id}?mode=notes`}><strong>原文注释 · PDF 第 {a.page_number} 页</strong><p>{a.note}</p></Link>)}</div></section>)}{shown.filter(n=>n.source_id&&!sources.some(s=>s.id===n.source_id)).map(card)}</>}</section>
}
