import type {InkDocument} from '../../../src/core/ink-types'
export type Draft={document:InkDocument;sequence:number;pending?:boolean;serverCopy?:InkDocument;owner?:string}
let database:Promise<IDBDatabase>|undefined
function open(){return database??=new Promise((resolve,reject)=>{const request=indexedDB.open('bbgddg-ink',1);request.onupgradeneeded=()=>request.result.createObjectStore('drafts');request.onsuccess=()=>resolve(request.result);request.onerror=()=>{database=undefined;reject(request.error)}})}
export async function readDraft(key:string):Promise<Draft|undefined>{const db=await open();return new Promise((resolve,reject)=>{const request=db.transaction('drafts').objectStore('drafts').get(key);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
// Claim and compare within read/write transactions, including across browser tabs.
export async function claimDraft(key:string,owner:string,fallback:Draft){const db=await open();return new Promise<Draft|undefined>((resolve,reject)=>{const tx=db.transaction('drafts','readwrite'),store=tx.objectStore('drafts'),request=store.get(key);let draft:Draft|undefined;request.onsuccess=()=>{draft=request.result;if(draft)store.put({...draft,owner},key);else store.put({...fallback,owner},key)};tx.oncomplete=()=>resolve(draft?.document?draft:undefined);tx.onerror=()=>reject(tx.error)})}
export async function writeDraft(key:string,draft:Draft){const db=await open();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('drafts','readwrite'),store=tx.objectStore('drafts'),request=store.get(key);let stale=false;request.onsuccess=()=>{const current=request.result as Draft|undefined;stale=!!draft.owner&&!!current?.owner&&(current.owner!==draft.owner||current.sequence>draft.sequence);if(stale){if(draft.pending!==false)store.put({...draft,pending:false},`${key}:conflict:${draft.owner}:${draft.sequence}`)}else store.put(draft,key)};tx.oncomplete=()=>stale?reject(new Error('此手写已在另一窗口打开，本机副本已保留，请下载副本后重新打开。')):resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
export const pendingInk=new Set<string>()
export async function hasPendingProjectInk(projectId:string){const db=await open();return new Promise<boolean>((resolve,reject)=>{const tx=db.transaction('drafts'),store=tx.objectStore('drafts'),keys=store.getAllKeys(),values=store.getAll();tx.oncomplete=()=>resolve([...pendingInk].some(key=>key.includes(projectId))||values.result.some((draft:Draft,i:number)=>String(keys.result[i]).includes(projectId)&&draft.pending!==false));tx.onerror=()=>reject(tx.error)})}
export async function hasPendingInk(projectId:string,targetId:string){const db=await open();const drafts=await new Promise<Draft[]>((resolve,reject)=>{const request=db.transaction('drafts').objectStore('drafts').getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});return [...pendingInk].some(key=>key.includes(projectId)&&key.includes(targetId))||drafts.some(d=>d.pending!==false&&(d.document.target.kind==='pdf'?d.document.target.sourceId===targetId:d.document.target.noteId===targetId))}
