import type {InkDocument} from '../../../src/core/ink-types'
export type Draft={document:InkDocument;sequence:number;pending?:boolean;serverCopy?:InkDocument}
let database:Promise<IDBDatabase>|undefined
function open(){return database??=new Promise((resolve,reject)=>{const request=indexedDB.open('bbgddg-ink',1);request.onupgradeneeded=()=>request.result.createObjectStore('drafts');request.onsuccess=()=>resolve(request.result);request.onerror=()=>{database=undefined;reject(request.error)}})}
export async function readDraft(key:string):Promise<Draft|undefined>{const db=await open();return new Promise((resolve,reject)=>{const request=db.transaction('drafts').objectStore('drafts').get(key);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
export async function writeDraft(key:string,draft:Draft){const db=await open();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('drafts','readwrite');tx.objectStore('drafts').put(draft,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
export const pendingInk=new Set<string>()
export async function hasPendingProjectInk(projectId:string){const db=await open();return new Promise<boolean>((resolve,reject)=>{const tx=db.transaction('drafts'),store=tx.objectStore('drafts'),keys=store.getAllKeys(),values=store.getAll();tx.oncomplete=()=>resolve([...pendingInk].some(key=>key.includes(projectId))||values.result.some((draft:Draft,i:number)=>String(keys.result[i]).includes(projectId)&&draft.pending!==false));tx.onerror=()=>reject(tx.error)})}
export async function hasPendingInk(projectId:string,targetId:string){const db=await open();const drafts=await new Promise<Draft[]>((resolve,reject)=>{const request=db.transaction('drafts').objectStore('drafts').getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});return [...pendingInk].some(key=>key.includes(projectId)&&key.includes(targetId))||drafts.some(d=>d.pending!==false&&(d.document.target.kind==='pdf'?d.document.target.sourceId===targetId:d.document.target.noteId===targetId))}
