import {useRef,useState,useMemo,useEffect} from 'react'
import type {InkBlock,InkPoint,InkStroke} from '../../../src/core/ink-types'
import {InkInput} from './input'
import {selectStrokes} from './lasso'
import {inverse,mapPoint,pathsIntersectWithin} from './geometry'
import type {Matrix} from './geometry'
export type InkMode='browse'|'pen'|'marker'|'line'|'eraser'|'lasso'|'text'|'region'
export default function InkCanvas({block,mode,color,width,onChange,onTextSelect,onRegionSelect,attachmentBase,viewportTransform=[1,0,0,1,0,0],canvasWidth=1000,canvasHeight=block.height,allowFingerDrawing=false,overlay=false}:{block:InkBlock;mode:InkMode;color:string;width:number;onChange:(block:InkBlock)=>void;onTextSelect?:(points:InkPoint[])=>void;onRegionSelect?:(points:InkPoint[])=>void;attachmentBase?:string;viewportTransform?:Matrix;canvasWidth?:number;canvasHeight?:number;allowFingerDrawing?:boolean;overlay?:boolean}){
 const input=useRef(new InkInput()),[active,setActive]=useState<InkPoint[]>([])
 const svg=useRef<SVGSVGElement>(null)
 function point(event:React.PointerEvent<SVGSVGElement>):InkPoint{const screen=svg.current!.getScreenCTM();if(!screen)throw new Error('画布不可见');const p=new DOMPoint(event.clientX,event.clientY).matrixTransform(screen.inverse());return {...mapPoint(p,inverse(viewportTransform)),pressure:event.pressure||.5}}
 function allowed(event:React.PointerEvent){return mode!=='browse'&&(event.pointerType==='pen'||event.pointerType==='mouse'||allowFingerDrawing)}
 const [selected,setSelected]=useState<string[]>([])
 const strokes=block.strokes
 useEffect(()=>{setSelected([]);input.current.cancel();setActive([])},[block.id])
 const preview:InkStroke={id:'active',tool:mode==='marker'?'marker':mode==='line'?'line':'pen',color,width,points:active}
 function shape(stroke:InkStroke){const points=stroke.tool==='line'&&stroke.points.length>1?[stroke.points[0],stroke.points.at(-1)!]:stroke.points;return <polyline key={stroke.id} data-ink-stroke={stroke.id==='active'?undefined:stroke.id} points={points.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke={stroke.color} strokeWidth={stroke.width*(stroke.tool==='marker'?5:1)} opacity={stroke.tool==='marker'?.32:1} strokeLinecap="round" strokeLinejoin="round"/>}
 const savedStrokes=useMemo(()=>strokes.map(shape),[strokes])
 function transformSelection(scale:number,dx=0,dy=0){const found=strokes.filter(s=>selected.includes(s.id)).flatMap(s=>s.points);if(!found.length)return;const bounds=found.reduce((b,p)=>({x:Math.min(b.x,p.x),y:Math.min(b.y,p.y)}),{x:Infinity,y:Infinity}),x=bounds.x,y=bounds.y;onChange({...block,strokes:strokes.map(s=>selected.includes(s.id)?{...s,points:s.points.map(p=>({...p,x:x+(p.x-x)*scale+dx,y:y+(p.y-y)*scale+dy}))}:s)})}
 return <>{selected.length>0&&<div className="ink-selection-actions" style={{position:overlay?'absolute':'relative',top:0,left:0,zIndex:6,display:'flex',flexWrap:'wrap',background:'var(--panel)'}} role="group" aria-label="选中笔迹操作"><span>已选 {selected.length} 笔</span><button onClick={()=>{onChange({...block,strokes:[...strokes,...strokes.filter(s=>selected.includes(s.id)).map(s=>({...s,id:crypto.randomUUID(),points:s.points.map(p=>({...p,x:p.x+20,y:p.y+20}))}))]});setSelected([])}}>复制笔迹</button><button onClick={()=>{onChange({...block,strokes:strokes.filter(s=>!selected.includes(s.id))});setSelected([])}}>删除笔迹</button><button onClick={()=>transformSelection(1,-20)}>左移</button><button onClick={()=>transformSelection(1,20)}>右移</button><button onClick={()=>transformSelection(1,0,-20)}>上移</button><button onClick={()=>transformSelection(1,0,20)}>下移</button><button onClick={()=>transformSelection(1.1)}>放大笔迹</button><button onClick={()=>transformSelection(.9)}>缩小笔迹</button><button onClick={()=>setSelected([])}>取消选择</button></div>}
 <svg ref={svg} data-ink-canvas aria-label="手写画布" viewBox={`0 0 ${canvasWidth} ${canvasHeight}`} style={{display:'block',width:'100%',height:overlay?'100%':'auto',position:overlay?'absolute':'relative',inset:overlay?0:undefined,zIndex:4,pointerEvents:mode==='browse'&&overlay?'none':'auto',touchAction:allowFingerDrawing&&mode!=='browse'?'none':'pan-x pan-y pinch-zoom',background:overlay?'transparent':'#fff'}}
 onPointerDown={event=>{if(!allowed(event))return;event.preventDefault();const p=point(event);if(!input.current.begin(event.pointerId,p)){setActive([]);return}try{event.currentTarget.setPointerCapture(event.pointerId)}catch{/* Synthetic pointer has no capture. */}setActive([p])}}
 onPointerMove={event=>{if(!allowed(event))return;const events=event.nativeEvent.getCoalescedEvents?.()||[];const points=(events.length?events:[event.nativeEvent]).map(e=>point({...event,clientX:e.clientX,clientY:e.clientY,pressure:e.pressure}));for(const p of points)input.current.move(event.pointerId,p);if(active.length)setActive(old=>[...old,...points])}}
 onPointerCancel={()=>{input.current.cancel();setActive([])}} onLostPointerCapture={()=>{input.current.cancel();setActive([])}}
 onPointerUp={event=>{if(!allowed(event))return;input.current.move(event.pointerId,point(event));const points=input.current.end(event.pointerId);setActive([]);if(!points.length)return;if(mode==='region'){onRegionSelect?.(points);return}if(mode==='text'){onTextSelect?.(points);return}if(mode==='lasso'){setSelected(selectStrokes(strokes,points));return}if(mode==='eraser'){const tolerance=width+8;const ids=new Set(strokes.filter(s=>pathsIntersectWithin(s.points,points,tolerance+s.width/2)).map(s=>s.id));onChange({...block,strokes:strokes.filter(s=>!ids.has(s.id))})}else onChange({...block,strokes:[...strokes,{...preview,id:crypto.randomUUID(),points}]})}}>
 {!overlay&&block.background!=='blank'&&<defs><pattern id={`paper-${block.id}`} width="40" height="40" patternUnits="userSpaceOnUse"><path d={block.background==='grid'?'M40 0H0V40':'M0 40H40'} stroke="#dce2ec" fill="none"/></pattern></defs>}
 {!overlay&&block.background!=='blank'&&<rect width="100%" height="100%" fill={`url(#paper-${block.id})`}/>}
 <g transform={`matrix(${viewportTransform.join(' ')})`}>{attachmentBase&&(block.images||[]).map(image=><image key={image.id} href={`${attachmentBase}/${image.attachmentId}`} x={image.x} y={image.y} width={image.width} height={image.height}/>)}{savedStrokes}{active.length>0&&mode!=='eraser'&&shape(preview)}</g>
 </svg></>
}
