import {useEffect,useState} from 'react'
import type {InkDocument} from '../../../src/core/ink-types'
import {buildAnnotationIndex} from './annotation-index'
export default function InkReview({projectId,sourceId,contentHash,onJump}:{projectId:string;sourceId:string;contentHash?:string|null;onJump:(page:number)=>void}){
 const [documents,setDocuments]=useState<InkDocument[]>([]),[kind,setKind]=useState('all'),[page,setPage]=useState(''),[color,setColor]=useState('all'),[error,setError]=useState('')
 useEffect(()=>{let active=true;async function load(){try{const response=await fetch(`/api/projects/${projectId}/ink/documents`);if(!response.ok)throw new Error('无法读取手写索引。');const data:InkDocument[]=await response.json();if(active)setDocuments(data.filter(d=>d.target.kind==='pdf'&&d.target.sourceId===sourceId))}catch(error){if(active)setError((error as Error).message)}}void load();window.addEventListener('bbgddg:ink-saved',load);return()=>{active=false;window.removeEventListener('bbgddg:ink-saved',load)}},[projectId,sourceId])
 const items=buildAnnotationIndex([],documents).filter(item=>(kind==='all'||item.kind===kind)&&(!page||item.page===Number(page))&&(color==='all'||item.color===color))
 return <section aria-label="手写标注索引"><h3>手写与划线 · {items.length}</h3><label>类型<select aria-label="手写标注类型" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">全部</option><option value="ink">手写</option><option value="underline">划线</option><option value="highlight">荧光笔</option></select></label><label>页码<input aria-label="手写标注页码" type="number" min="1" value={page} onChange={e=>setPage(e.target.value)}/></label><label>颜色<select aria-label="手写标注颜色" value={color} onChange={e=>setColor(e.target.value)}><option value="all">全部</option>{[...new Set(items.map(item=>item.color))].map(c=><option key={c} value={c}>{c}</option>)}</select></label>{documents.some(d=>d.target.kind==='pdf'&&d.target.contentHash!==contentHash)&&<p role="alert">部分笔迹对应旧版原文，跳转前请核对。</p>}{error&&<p role="alert">{error}</p>}{items.map(item=><button key={item.id} className="annotation-card" onClick={()=>onJump(item.page)}><span>第 {item.page} 页 · {item.kind==='underline'?'划线':item.kind==='highlight'?'荧光笔':'手写'}</span><span style={{color:item.color}}> ● </span></button>)}</section>
}
