import {useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {projectsApi,type Project} from '../lib/api'
import {NewProjectModal} from './ProjectsPage'
import {Brand,EmptyState} from '../components/WorkspaceUI'
import {timeAgo} from '../lib/time'
import AiControlPanel from '../components/AiControlPanel'
export default function LibraryPage(){
 const [projects,setProjects]=useState<Project[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[modal,setModal]=useState(false),[error,setError]=useState('')
 useEffect(()=>{projectsApi.list().then(setProjects).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[])
 async function remove(project:Project){if(!confirm(`删除项目“${project.title}”及其中的文献、笔记吗？`))return;try{await projectsApi.delete(project.id);setProjects(previous=>previous.filter(p=>p.id!==project.id))}catch(e){setError(e instanceof Error?e.message:'删除失败，请重试。')}}
 const shown=projects.filter(p=>`${p.title} ${p.description}`.toLowerCase().includes(query.toLowerCase()))
 return <div className="workbench"><aside className="navigation"><Brand/><div className="nav-section"><span className="nav-active">我的文献库 <span>{projects.length}</span></span><p>一个项目，一条研究线索。<br/>文献、对话与笔记都在这里。</p></div><div className="nav-bottom"><span className="status-dot"/>本地工作区<small>文献保存在这台电脑</small></div></aside><main id="main-content" className="library-main"><header className="page-heading"><div><p className="breadcrumb">文献库</p><h1>我的研究项目</h1><p>从一篇论文开始，把理解留在笔记里。</p></div><button className="primary" onClick={()=>setModal(true)}>＋ 新建项目</button></header><AiControlPanel/><div className="library-tools"><label className="search-field"><span aria-hidden="true">⌕</span><input name="projectSearch" autoComplete="off" aria-label="搜索项目" placeholder="搜索项目名称或描述…" value={query} onChange={e=>setQuery(e.target.value)}/></label><span>{shown.length} 个项目</span></div>{error&&<p role="alert" className="error-message">{error}</p>}{loading?<div className="empty-state"><span className="spinner"/>正在加载项目…</div>:<div className="project-list">{shown.map(project=><article className="project-card" key={project.id}><Link to={`/projects/${project.id}`} className="project-card-link"><span className="project-file-icon" aria-hidden="true">▤</span><div><h2>{project.title}</h2><p>{project.description||'添加文献，开始阅读与记录。'}</p><div className="project-meta"><span>{project.source_count} 篇文献</span><span>{project.note_count} 篇笔记</span><span>{timeAgo(project.accessed_at)}</span></div></div><span className="open-project" aria-hidden="true">↗</span></Link><button className="project-delete" aria-label={`删除项目${project.title}`} onClick={()=>remove(project)}>删除</button></article>)}</div>}{!loading&&!shown.length&&<EmptyState title={query?'没有匹配的项目':'开始你的第一个研究项目'}>{query?'尝试其他关键词。':'点击“新建项目”，然后添加本地 PDF 或论文链接。'}</EmptyState>}<footer className="library-footer">PDFPal <span>为认真阅读留出空间。</span></footer></main>{modal&&<NewProjectModal onClose={()=>setModal(false)} onCreate={project=>{setProjects(previous=>[project,...previous]);setModal(false)}}/>}</div>
}
