import {test,expect} from '@playwright/test'
import {zipSync,strToU8} from 'fflate'
import {createProjectViaApi} from './helpers'

test('drag mixed files imports valid documents and reports failures without navigating away',async({page})=>{
  const project=await createProjectViaApi(page,'Drag Documents')
  await page.goto(`/projects/${project.id}`)
  await page.getByTestId('document-drop-zone').evaluate(node=>{
    const data=new DataTransfer()
    data.items.add(new File(['# Alpha\n\nResearch Beta'],'study.md',{type:'text/markdown'}))
    data.items.add(new File(['plain text'],'study.txt',{type:'text/plain'}))
    data.items.add(new File(['unsupported'],'bad.doc',{type:'application/msword'}))
    node.dispatchEvent(new DragEvent('dragover',{bubbles:true,cancelable:true,dataTransfer:data}))
    node.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:data}))
  })
  await expect(page.getByRole('status')).toContainText('2 成功，1 失败')
  await expect(page.getByRole('alert')).toContainText('bad.doc')
  await page.getByText('study.md',{exact:true}).click()
  await expect(page.locator('[data-paragraph="2"]')).toContainText('Research Beta')
  await expect(page.getByRole('heading',{name:'Alpha',exact:true})).toBeVisible()
  await page.locator('[data-paragraph="2"]').evaluate(node=>{
    const range=document.createRange();range.selectNodeContents(node.querySelector('p')!)
    const selection=window.getSelection()!;selection.removeAllRanges();selection.addRange(range)
    node.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}))
  })
  await page.getByRole('button',{name:'添加原文笔记',exact:true}).click()
  await page.getByLabel('笔记正文',{exact:true}).fill('我的理解')
  await page.getByRole('button',{name:'保存笔记',exact:true}).click()
  await expect(page.locator('.note-toolbar [role=status]')).toContainText('已保存')
  await expect(page.getByRole('button',{name:/回到原文.*第 2 段/})).toBeVisible()
  await page.reload()
  await page.getByRole('button',{name:'笔记',exact:true}).click()
  await page.getByRole('navigation',{name:'笔记列表'}).getByRole('button').first().click()
  await expect(page.getByRole('button',{name:/回到原文.*第 2 段/})).toBeVisible()
  await page.getByRole('button',{name:/回到原文.*第 2 段/}).click()
  await expect(page.locator('[data-paragraph="2"]')).toHaveClass(/is-target/)
})

test('DOCX via file picker displays heading and paragraphs',async({page})=>{
  const project=await createProjectViaApi(page,'Word Documents')
  await page.goto(`/projects/${project.id}`)
  await page.getByRole('button',{name:'＋ 添加文献',exact:true}).click()
  await page.getByRole('button',{name:/本地文档/}).click()
  const buffer=Buffer.from(zipSync({'word/document.xml':strToU8('<w:document xmlns:w="urn:w"><w:body><w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:t>Word Heading</w:t></w:r></w:p><w:p><w:r><w:t>Word paragraph</w:t></w:r></w:p></w:body></w:document>')}))
  await page.locator('input[type=file]').setInputFiles({name:'study.docx',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',buffer})
  await page.getByRole('button',{name:'导入文档',exact:true}).click()
  await page.getByText('study.docx',{exact:true}).click()
  await expect(page.getByRole('heading',{name:'Word Heading',exact:true})).toBeVisible()
  await expect(page.locator('[data-paragraph="2"]')).toContainText('Word paragraph')
  await page.setViewportSize({width:390,height:844})
  await page.locator('.reader-header-actions').getByRole('button',{name:'收起面板',exact:true}).click()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true)
  await page.screenshot({path:'../../document-import-mobile.png'})
})
