import {test,expect} from '@playwright/test'
import {createProjectViaApi} from './helpers'
import fs from 'node:fs'
async function notePage(page:any){const project=await createProjectViaApi(page,'手写验证');const note=await(await page.request.post(`/api/projects/${project.id}/notes`,{data:{title:'中文公式笔记',content:'理解公式 $x^2$'}})).json();await page.goto(`/projects/${project.id}/notes/${note.id}`);return {project,note}}
async function draw(canvas:any,points:number[][]){await canvas.evaluate((el:Element,points:number[][])=>{const box=el.getBoundingClientRect();for(let i=0;i<points.length;i++)el.dispatchEvent(new PointerEvent(i===0?'pointerdown':i===points.length-1?'pointerup':'pointermove',{bubbles:true,pointerId:17,pointerType:'pen',clientX:box.left+points[i][0],clientY:box.top+points[i][1],pressure:.5}))},points)}
test('lasso copy and erase can be undone without changing Markdown',async({page})=>{
 await notePage(page)
 await page.getByRole('button',{name:'添加手写块',exact:true}).click()
 await page.getByRole('button',{name:'钢笔',exact:true}).click()
 const canvas=page.locator('[data-ink-canvas]')
 await draw(canvas,[[30,40],[60,70],[90,100]])
 await expect(canvas.locator('[data-ink-stroke]')).toHaveCount(1)
 await page.getByRole('button',{name:'套索选择',exact:true}).click()
 await draw(canvas,[[5,5],[120,5],[120,130],[5,130],[5,5]])
 await page.getByRole('button',{name:'复制笔迹',exact:true}).click()
 await expect(canvas.locator('[data-ink-stroke]')).toHaveCount(2)
 await page.getByRole('button',{name:'撤销手写',exact:true}).click()
 await expect(canvas.locator('[data-ink-stroke]')).toHaveCount(1)
 await page.getByRole('button',{name:'整笔橡皮',exact:true}).click()
 await draw(canvas,[[30,40],[60,70],[90,100]])
 await expect(canvas.locator('[data-ink-stroke]')).toHaveCount(0)
 await page.getByRole('button',{name:'撤销手写',exact:true}).click()
 await expect(canvas.locator('[data-ink-stroke]')).toHaveCount(1)
 await expect(page.locator('.prose.note-body')).toContainText('理解公式')
})
test('mixed note print view includes Chinese, formula and ink',async({page})=>{
 await page.addInitScript(()=>{window.print=()=>{}})
 await notePage(page)
 await page.getByRole('button',{name:'添加手写块',exact:true}).click()
 await expect(page.getByText('手写已保存',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'打印笔记 / 存储为 PDF',exact:true}).click()
 const print=page.frameLocator('iframe[title="笔记打印预览"]')
 await expect(print.getByRole('heading',{name:'中文公式笔记'})).toHaveCount(1)
 await expect(print.locator('.katex')).toHaveCount(1)
 await expect(print.locator('svg')).toHaveCount(1)
})
test('explicit Pencil text selection exposes actions without auto sending AI',async({page})=>{
 const project=await createProjectViaApi(page,'Pencil选字')
 const source=await(await page.request.post(`/api/projects/${project.id}/sources/upload`,{multipart:{file:{name:'教材.pdf',mimeType:'application/pdf',buffer:fs.readFileSync(new URL('../../test/fixtures/sample.pdf',import.meta.url))}}})).json()
 await page.goto(`/projects/${project.id}/sources/${source.id}`)
 await page.getByRole('button',{name:'文字选择',exact:true}).click()
 const text=page.locator('[data-pdf-page="1"] .textLayer span').first()
 await expect(text).toBeVisible()
 const box=await text.boundingBox()
 const canvas=page.locator('[data-pdf-page="1"] [data-ink-canvas]'),surface=await canvas.boundingBox()
 await draw(canvas,[[box!.x-surface!.x+1,box!.y-surface!.y+box!.height/2],[box!.x-surface!.x+box!.width-1,box!.y-surface!.y+box!.height/2]])
 await expect(page.getByRole('button',{name:'高亮',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'高亮',exact:true}).click()
 await expect(page.locator('[data-annotation-id]')).toHaveCount(1)
 await draw(canvas,[[box!.x-surface!.x+1,box!.y-surface!.y+box!.height/2],[box!.x-surface!.x+box!.width-1,box!.y-surface!.y+box!.height/2]])
 await page.getByRole('button',{name:'下划线',exact:true}).click()
 await expect(page.locator('[data-pdf-page="1"] [data-ink-stroke]')).toHaveCount(1)
})
