import {test,expect} from '@playwright/test'
import {createProjectViaApi} from './helpers'
test('failed upload keeps local draft across reload and retries',async({page})=>{
 const project=await createProjectViaApi(page,'手写恢复')
 const note=await(await page.request.post(`/api/projects/${project.id}/notes`,{data:{title:'恢复',content:'正文'}})).json()
 await page.route('**/ink',route=>route.request().method()==='PUT'?route.fulfill({status:503,body:'{}'}):route.continue())
 await page.goto(`/projects/${project.id}/notes/${note.id}`)
 await page.getByRole('button',{name:'添加手写块',exact:true}).click()
 await expect(page.getByText('手写保存失败，待重试',{exact:true})).toBeVisible()
 await page.reload()
 await expect(page.locator('[data-ink-canvas]')).toHaveCount(1)
 await page.unroute('**/ink')
 await page.getByRole('button',{name:'重试手写保存',exact:true}).click()
 await expect(page.getByText('手写已保存',{exact:true})).toBeVisible()
})
test('conflict keeps local and remote versions and explicit server adoption retains a copy',async({page})=>{
 const project=await createProjectViaApi(page,'手写冲突')
 const note=await(await page.request.post(`/api/projects/${project.id}/notes`,{data:{title:'冲突'}})).json(),url=`/api/projects/${project.id}/ink`
 await page.goto(`/projects/${project.id}/notes/${note.id}`)
 await page.getByRole('button',{name:'添加手写块',exact:true}).click()
 await expect(page.getByText('手写已保存',{exact:true})).toBeVisible()
 const remote=await(await page.request.get(`${url}?kind=note&noteId=${note.id}`)).json();remote.blocks[0].background='grid'
 await page.request.put(url,{data:{document:remote,expectedRevision:remote.revision}})
 await page.getByRole('button',{name:'添加手写块',exact:true}).click()
 await expect(page.getByRole('button',{name:'下载冲突副本',exact:true})).toBeVisible()
 await expect(page.locator('[data-ink-canvas]')).toHaveCount(2)
 page.once('dialog',dialog=>dialog.accept())
 await page.getByRole('button',{name:'采用服务器版本',exact:true}).click()
 await expect(page.locator('[data-ink-canvas]')).toHaveCount(1)
 await expect(page.getByLabel('手写纸张')).toHaveValue('grid')
 await page.getByRole('button',{name:'撤销手写',exact:true}).click()
 await expect(page.locator('[data-ink-canvas]')).toHaveCount(1)
 await expect(page.getByLabel('手写纸张')).toHaveValue('grid')
})

test('an old mounted window cannot overwrite a newer persisted draft',async({page,context})=>{
 const project=await createProjectViaApi(page,'草稿竞争'),note=await(await page.request.post(`/api/projects/${project.id}/notes`,{data:{title:'竞争'}})).json()
 let release!:()=>void;const held=new Promise<void>(resolve=>release=resolve)
 await page.route('**/ink',async route=>{if(route.request().method()==='PUT'){await held;await route.continue()}else await route.continue()})
 await page.goto(`/projects/${project.id}/notes/${note.id}`)
 await page.getByRole('button',{name:'添加手写块',exact:true}).click()
 await expect(page.getByText('手写保存中…',{exact:true})).toBeVisible()
 await page.waitForTimeout(700)
 const newer=await context.newPage()
 await newer.route('**/ink',route=>route.request().method()==='PUT'?route.fulfill({status:503,body:'{}'}):route.continue())
 await newer.goto(`/projects/${project.id}/notes/${note.id}`)
 await expect(newer.locator('[data-ink-canvas]')).toHaveCount(1)
 await newer.getByRole('button',{name:'添加手写块',exact:true}).click()
 await expect(newer.getByText('手写保存失败，待重试',{exact:true})).toBeVisible()
 release();await page.waitForTimeout(700)
 await newer.reload()
 await expect(newer.locator('[data-ink-canvas]')).toHaveCount(2)
 await newer.close()
})
