import {test,expect} from '@playwright/test'
import {createProjectViaApi} from './helpers'
import fs from 'node:fs'
import {PDFDocument} from 'pdf-lib'
test('annotated PDF downloads as a new document and reader fits tablet',async({page})=>{
 const project=await createProjectViaApi(page,'导出文献')
 const source=await(await page.request.post(`/api/projects/${project.id}/sources/upload`,{multipart:{file:{name:'教材.pdf',mimeType:'application/pdf',buffer:fs.readFileSync(new URL('../../test/fixtures/sample.pdf',import.meta.url))}}})).json()
 await page.setViewportSize({width:820,height:1180})
 await page.goto(`/projects/${project.id}/sources/${source.id}`)
 await expect(page.locator('[data-pdf-page="1"][data-pdf-ready="true"]')).toBeVisible()
 await page.getByRole('button',{name:'导出标注 PDF',exact:true}).click()
 const downloadPromise=page.waitForEvent('download')
 await page.getByRole('button',{name:'下载 PDF 副本',exact:true}).click()
 const download=await downloadPromise,bytes=fs.readFileSync((await download.path())!)
 expect((await PDFDocument.load(bytes)).getPageCount()).toBe(source.pages)
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:'../docs/validation/ipad-reader.png'})
 await page.setViewportSize({width:390,height:700})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
test('settings backup restores editable note ink into a selected project',async({page})=>{
 const project=await createProjectViaApi(page,'备份来源'),target=await createProjectViaApi(page,'恢复目标')
 const note=await(await page.request.post(`/api/projects/${project.id}/notes`,{data:{title:'保留笔记',content:'保留文字'}})).json()
 await page.request.put(`/api/projects/${project.id}/ink`,{data:{expectedRevision:0,document:{version:1,revision:0,target:{kind:'note',noteId:note.id},blocks:[{id:'b',height:600,background:'grid',strokes:[{id:'s',tool:'pen',color:'#111827',width:2,points:[{x:20,y:30},{x:50,y:60}]}]}]}}})
 await page.goto('/settings')
 await page.getByLabel('备份项目').selectOption(project.id)
 const downloadPromise=page.waitForEvent('download')
 await page.getByRole('button',{name:'下载笔记与标注备份',exact:true}).click()
 const file=await(await downloadPromise).path()
 await page.getByLabel('备份项目').selectOption(target.id)
 page.once('dialog',dialog=>dialog.accept())
 await page.getByLabel('恢复备份文件').setInputFiles(file!)
 await expect(page.getByText(/恢复 \d+ 项，重复 \d+ 项，缺少原文 \d+ 份/)).toBeVisible()
 const notes=await(await page.request.get(`/api/projects/${target.id}/notes`)).json()
 const restored=notes.find((n:any)=>n.title==='保留笔记')
 expect(restored).toBeTruthy()
 await page.goto(`/projects/${target.id}/notes/${restored.id}`)
 await expect(page.locator('[data-ink-stroke]')).toHaveCount(1)
 await page.setViewportSize({width:820,height:1180})
 await page.locator('.note-ink').scrollIntoViewIfNeeded()
 await page.screenshot({path:'../docs/validation/ipad-notes.png'})
})
