import fs from 'node:fs'
import {test,expect,type Page} from '@playwright/test'
import {createProjectViaApi} from './helpers'

async function fixture(page:Page){
 const project=await createProjectViaApi(page,'教材学习')
 const response=await page.request.post(`/api/projects/${project.id}/sources/upload`,{multipart:{file:{name:'教材.pdf',mimeType:'application/pdf',buffer:fs.readFileSync(new URL('../../test/fixtures/sample.pdf',import.meta.url))}}})
 expect(response.ok()).toBeTruthy();const source=await response.json()
 return {project,source}
}
test('source note retains its draft across tabs, collapse and review; saved anchor jumps accurately',async({page})=>{
 const {project,source}=await fixture(page)
 const response=await page.request.post(`/api/projects/${project.id}/notes`,{data:{source_id:source.id,title:'概念笔记',content:'理解内容',tags:['复习'],anchors:[{sourceId:source.id,page:1,text:'Test page 1',rects:[{x1:.12,y1:.2,x2:.5,y2:.25}]}]}})
 expect(response.ok()).toBeTruthy();const note=await response.json()
 await page.goto(`/projects/${project.id}/notes/${note.id}`)
 await page.getByRole('button',{name:'编辑正文',exact:true}).click()
 await page.getByLabel('笔记正文').fill('自己的理解与公式 $x^2$')
 await page.getByRole('button',{name:'AI 问答',exact:true}).click()
 await page.getByRole('button',{name:'笔记',exact:true}).click()
 await expect(page.getByLabel('笔记正文')).toHaveValue('自己的理解与公式 $x^2$')
 await page.getByRole('button',{name:'收起原文',exact:true}).click()
 await page.getByRole('button',{name:'显示原文',exact:true}).click()
 await page.getByRole('button',{name:'保存笔记',exact:true}).click()
 await expect(page.getByRole('status')).toHaveText('已保存')
 await page.getByRole('button',{name:/回到原文/}).click()
 await expect(page.locator('[data-citation-highlight]')).toBeVisible()
 const saved=await(await page.request.get(`/api/projects/${project.id}/notes/${note.id}`)).json()
 expect(saved.content).toContain('自己的理解');expect(saved.anchors[0].rects[0].x1).toBe(.12)
 await page.screenshot({path:test.info().outputPath('review-desktop.png')})
})
test('failed note save preserves a draft and can be retried',async({page})=>{
 const project=await createProjectViaApi(page)
 const note=await(await page.request.post(`/api/projects/${project.id}/notes`,{data:{title:'计划'}})).json()
 await page.goto(`/projects/${project.id}/notes/${note.id}`)
 await page.getByRole('button',{name:'编辑正文',exact:true}).click()
 await page.getByLabel('笔记正文').fill('明天复习第一章')
 await page.route('**/notes/'+note.id,route=>route.request().method()==='PUT'?route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({detail:'测试保存失败'})}):route.continue())
 await page.getByRole('button',{name:'保存笔记',exact:true}).click()
 await expect(page.getByRole('alert')).toContainText('草稿已保留')
 await page.reload();await page.getByRole('button',{name:'编辑正文',exact:true}).click()
 await expect(page.getByLabel('笔记正文')).toHaveValue('明天复习第一章')
 await page.unroute('**/notes/'+note.id)
 await page.getByRole('button',{name:'保存笔记',exact:true}).click();await expect(page.getByRole('status')).toHaveText('已保存')
})
test('selected passage answer survives tool switching and can be saved with its original anchor',async({page})=>{
 const {project,source}=await fixture(page)
 await page.goto(`/projects/${project.id}/sources/${source.id}`)
 const text=page.locator('[data-pdf-page="1"] .textLayer span').first();await expect(text).toBeVisible()
 await text.evaluate(span=>{const range=document.createRange();range.selectNodeContents(span);const selected=window.getSelection()!;selected.removeAllRanges();selected.addRange(range);document.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}))})
 await page.getByRole('button',{name:'提问',exact:true}).click()
 let finish:()=>void=()=>{}
 const waiting=new Promise<void>(resolve=>{finish=resolve})
 await page.route('**/api/chat',async route=>{await waiting;await route.fulfill({status:200,contentType:'text/event-stream',body:'data: '+JSON.stringify({text:'解释与推导 $x^2$',contextScope:'selection'})+'\n\ndata: [DONE]\n\n'})})
 await page.getByPlaceholder('输入问题…（Enter 发送，Shift+Enter 换行）').fill('解释这段')
 await page.getByRole('button',{name:'发送问题'}).click()
 await page.getByRole('button',{name:'笔记',exact:true}).click()
 await page.getByRole('button',{name:'AI 问答',exact:true}).click();finish()
 await expect(page.locator('.chat-answer')).toContainText('解释与推导')
 await page.getByRole('button',{name:'摘入笔记',exact:true}).click()
 await expect(page.getByLabel('笔记正文')).toHaveValue(/解释与推导/)
 await page.getByRole('button',{name:'保存笔记',exact:true}).click();await expect(page.getByRole('status')).toHaveText('已保存')
 const notes=await(await page.request.get(`/api/projects/${project.id}/sources/${source.id}/notes`)).json()
 expect(notes[0].anchors[0].page).toBe(1);expect(notes[0].anchors[0].rects.length).toBeGreaterThan(0);expect(notes[0].origin.kind).toBe('ai')
})
for(const viewport of [{width:390,height:844},{width:1024,height:1366}])test(`reading tools fit ${viewport.width}px and restore after collapse`,async({page})=>{
 await page.setViewportSize(viewport)
 const {project,source}=await fixture(page)
 await page.goto(`/projects/${project.id}/sources/${source.id}`)
 await expect(page.locator('[data-pdf-page="1"]')).toHaveAttribute('data-pdf-ready','true')
 if(viewport.width<900)await page.getByRole('navigation',{name:'平板阅读工具'}).getByRole('button',{name:'打开笔记',exact:true}).click();else await page.getByRole('button',{name:'笔记',exact:true}).click()
 await page.getByRole('button',{name:'新建笔记',exact:true}).click()
 await page.getByLabel('笔记正文').fill('移动阅读草稿')
 await page.getByRole('button',{name:'收起面板',exact:true}).last().click()
 if(viewport.width<900)await page.getByRole('navigation',{name:'平板阅读工具'}).getByRole('button',{name:'打开笔记',exact:true}).click();else await page.locator('.study-rail').getByRole('button',{name:'笔记',exact:true}).click()
 await expect(page.getByLabel('笔记正文')).toHaveValue('移动阅读草稿')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
 await page.screenshot({path:test.info().outputPath(`reading-${viewport.width}.png`)})
})
test('phone review starts with notes, then expands the original on demand',async({page})=>{
 await page.setViewportSize({width:390,height:844})
 const {project,source}=await fixture(page)
 await page.goto(`/projects/${project.id}/sources/${source.id}?mode=notes`)
 await expect(page.getByLabel('文献笔记编辑器')).toBeVisible()
 await expect(page.getByTestId('pdf-scroll-area')).toBeHidden()
 await page.getByRole('button',{name:'显示原文',exact:true}).click()
 await expect(page.getByTestId('pdf-scroll-area')).toBeVisible()
 await page.getByRole('button',{name:'收起原文',exact:true}).click()
 await expect(page.getByLabel('文献笔记编辑器')).toBeVisible()
})
