import {test,expect} from '@playwright/test'
import {createProjectViaApi} from './helpers'
import fs from 'node:fs'
test('reader adapts narrow split windows without losing a note draft',async({page})=>{
 const project=await createProjectViaApi(page,'平板阅读')
 const response=await page.request.post(`/api/projects/${project.id}/sources/upload`,{multipart:{file:{name:'教材.pdf',mimeType:'application/pdf',buffer:fs.readFileSync(new URL('../../test/fixtures/sample.pdf',import.meta.url))}}})
 const source=await response.json()
 await page.setViewportSize({width:1024,height:768})
 await page.goto(`/projects/${project.id}/sources/${source.id}`)
 await page.getByRole('button',{name:'笔记',exact:true}).click()
 await page.getByRole('button',{name:'新建笔记',exact:true}).click()
 await page.getByLabel('笔记正文').fill('旋转后继续写作')
 await expect(page.getByRole('separator',{name:'调整阅读面板宽度'})).toBeVisible()
 await page.setViewportSize({width:820,height:1024})
 const tools=page.getByRole('navigation',{name:'平板阅读工具'})
 await expect(tools).toBeVisible()
 await tools.getByRole('button',{name:'打开标注',exact:true}).click()
 await tools.getByRole('button',{name:'打开笔记',exact:true}).click()
 await expect(page.getByLabel('笔记正文')).toHaveValue('旋转后继续写作')
 await page.setViewportSize({width:390,height:650})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.setViewportSize({width:1024,height:768})
 await expect(page.getByLabel('笔记正文')).toHaveValue('旋转后继续写作')
})

test('tablet review opens its tool rather than covering it with the original',async({page})=>{
 const project=await createProjectViaApi(page,'复习面板')
 const response=await page.request.post(`/api/projects/${project.id}/sources/upload`,{multipart:{file:{name:'教材.pdf',mimeType:'application/pdf',buffer:fs.readFileSync(new URL('../../test/fixtures/sample.pdf',import.meta.url))}}})
 const source=await response.json()
 await page.setViewportSize({width:820,height:1024})
 await page.goto(`/projects/${project.id}/sources/${source.id}?mode=notes`)
 await page.getByRole('button',{name:'打开笔记',exact:true}).click()
 await page.getByRole('button',{name:'新建笔记',exact:true}).click({timeout:5000})
 await expect(page.getByLabel('笔记正文')).toBeVisible()
 await expect(page.getByTestId('pdf-scroll-area')).toBeHidden()
})
test('narrow reader tool drawer enters and restores keyboard focus',async({page})=>{
 const project=await createProjectViaApi(page,'键盘焦点')
 const response=await page.request.post(`/api/projects/${project.id}/sources/upload`,{multipart:{file:{name:'教材.pdf',mimeType:'application/pdf',buffer:fs.readFileSync(new URL('../../test/fixtures/sample.pdf',import.meta.url))}}})
 const source=await response.json()
 await page.setViewportSize({width:820,height:1024})
 await page.goto(`/projects/${project.id}/sources/${source.id}`)
 const trigger=page.getByRole('button',{name:'打开笔记',exact:true})
 await trigger.click()
 const drawer=page.locator('.study-panel')
 expect(await drawer.evaluate(el=>el.contains(document.activeElement))).toBe(true)
 await page.keyboard.press('Escape')
 await expect(drawer).toBeHidden()
 await expect(trigger).toBeFocused()
})
